import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1360,height:900}});const errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.addInitScript(()=>{window.__MIYU_DESKTOP__=true;window.__MIYU_API_TOKEN__='test-native-session';window.miyuLoad=async()=>'';window.miyuSave=async x=>{window.savedNativeState=x;};window.windowCalls=[];window.miyuWindow=async(...args)=>{window.windowCalls.push(args);};});
const html=await fs.readFile('desktop/ui.html','utf8');
await page.route('https://miyu.test/',r=>r.fulfill({status:200,headers:{'Content-Type':'text/html','Content-Security-Policy':"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; media-src data: blob:; connect-src 'self'; object-src 'none'; frame-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"},body:html}));
await page.route('https://miyu.test/api/chat',r=>{expect(r.request().headers()['x-miyu-token']).toBe('test-native-session');return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({content:'Hello from the native bridge mock.'})});});
await page.goto('https://miyu.test/');await page.waitForFunction(()=>window.miyuStatus?.().avatarReady);
await expect(page.locator('#download-button')).toContainText('Desktop edition');
await page.locator('#pin-button').click();await expect(page.locator('#pin-button')).toHaveAttribute('aria-pressed','true');await page.locator('#compact-button').click();await page.keyboard.press('Escape');
expect(await page.evaluate(()=>window.windowCalls)).toEqual([['pin',true],['compact',true],['compact',false]]);
await page.locator('#connection-pill').click();await page.locator('#ai-provider').selectOption('ollama');await page.locator('#test-connection').click();await expect(page.locator('#connection-result')).toContainText('Connected');await page.locator('[data-action="save-connection"]').click();
await page.locator('#chat-input').fill('Hello Miyu');await page.locator('#chat-input').press('Enter');await expect(page.locator('.message-bubble').last()).toContainText('Hello from the native bridge mock.');
await page.locator('[data-action="personalize"]').click();await page.waitForTimeout(500);await page.screenshot({path:'tests/native-settings.png'});
await page.locator('.modal-header [data-action="close-modal"]').click();await page.waitForTimeout(250);
expect(errors).toEqual([]);console.log('PASS native UI under production CSP, native state/window bindings, same-origin API routing (mock native host).');console.log('No CSP or JavaScript errors. This is not a Windows runtime test.');
await browser.close();
